# Generated by Django 5.0.6 on 2024-06-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_rename_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
