# Generated by Django 5.0.6 on 2024-06-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='task',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.employee'),
            preserve_default=False,
        ),
    ]
