# Generated by Django 5.0.6 on 2024-06-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_remove_task_employer_id_task_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_manager.employee'),
        ),
    ]
